version: "3.7"
                           
services:
  mongo-setup:
    image: mongo
    restart: on-failure
    entrypoint: ["bash", "/scripts/make_all_in_one_go.sh"]   
    volumes:
      - ./scripts:/scripts   
    env_file:
      - .env
    depends_on:
      - mongo1_rs1
      - mongo2_rs1
      - mongo3_rs1
    networks:
      - horizon-net

networks:
  horizon-net: