version: "3.7"
#  ____  ____   ___   _______     _____  ________    ___   ____  _____  
# |_   ||   _|.'   `.|_   __ \   |_   _||  __   _| .'   `.|_   \|_   _| 
#   | |__| | /  .-.  \ | |__) |    | |  |_/  / /  /  .-.  \ |   \ | |   
#   |  __  | | |   | | |  __ /     | |     .'.' _ | |   | | | |\ \| |   
#  _| |  | |_\  `-'  /_| |  \ \_  _| |_  _/ /__/ |\  `-'  /_| |_\   |_  
# |____||____|`.___.'|____| |___||_____||________| `.___.'|_____|\____| 
#   _____     ____     _____   ______                                   
#  / ___ `. .'    '.  / ___ `./ ____ `.                                 
# |_/___) ||  .--.  ||_/___) |`'  __) |                                 
#  .'____.'| |    | | .'____.'_  |__ '.                                 
# / /_____ |  `--'  |/ /_____| \____) |                                 
# |_______| '.____.' |_______|\______.'                                 

services:
  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - '${CACHE_PORT}:${CACHE_PORT}'
    command: redis-server --loglevel warning --requirepass ${CACHE_PASSWORD}
    volumes: 
      - ./cache:/data
    env_file:
      - .env
    networks:
      - horizon-net
  mongo-setup:
    image: mongo
    entrypoint: ["bash", "/scripts/make_all_in_one_go.sh"]   
    volumes:
      - ./scripts:/scripts   
    env_file:
      - .env
    depends_on:
      - mongo1_rs1
      - mongo2_rs1
      - mongo3_rs1
    networks:
      - horizon-net

  database:
    image: mongo
    restart: always 
    command: mongos --port ${DATABASE_PORT} --configdb configsvr/configsvr:${CONFIG_SERVER_PORT} --bind_ip_all
    expose:  
      - ${DATABASE_PORT}
    ports:  
      - ${DATABASE_PORT}:${DATABASE_PORT}
    env_file:
      - .env
    networks:
      - horizon-net
  configsvr:
    image: mongo
    restart: always
    command: mongod --port ${CONFIG_SERVER_PORT} --configsvr --replSet ${REPLICA_SET_NAME_1}
    expose:
      - ${CONFIG_SERVER_PORT}
    networks:
      - horizon-net
    env_file:
      - .env
    depends_on:
      - mongo1_rs1
networks:
  horizon-net: