version: "3.7"

# Our containers
services:
  base:
    &mongo
    image: mongo
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - horizon-net

  mongo1_rs1:
    <<: *mongo
    expose:
      - ${DB1_RS1_PORT}
    volumes:
      - ./mongo-volumes/mongo1_1/data/db:/data/db
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "${REPLICA_SET_NAME_1}", "--journal", "--dbpath", "/data/db", "--port", "${DB1_RS1_PORT}"]

  mongo2_rs1:
    <<: *mongo
    expose:  
      - ${DB2_RS1_PORT}
    volumes:
      - ./mongo-volumes/mongo2_1/data/db:/data/db
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "${REPLICA_SET_NAME_1}", "--journal", "--dbpath", "/data/db", "--port", "${DB2_RS1_PORT}"]

  mongo3_rs1:
    <<: *mongo
    expose:
      - ${DB3_RS1_PORT}
    volumes:
      - ./mongo-volumes/mongo3_1/data/db:/data/db
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "${REPLICA_SET_NAME_1}", "--journal", "--dbpath", "/data/db", "--port", "${DB3_RS1_PORT}"]
